"""
MiniStack MCP Server — the knowledge layer for AI agents.

Exposes a stable, version-pinned view of MiniStack to any IDE that speaks
MCP (Claude Desktop, Cursor, Continue, Windsurf, Cline, etc.).

The data comes from a static catalog generated by ``build_catalog.py`` plus
hand-curated parity notes in ``parity.json``. The server itself never
re-parses the codebase at request time, so AI agents get deterministic,
fast answers and the knowledge tracks the shipped MiniStack version.

Tools:
  - ministack_version            — version, endpoint, default account/region
  - ministack_health             — live probe against the running emulator
  - ministack_reset              — POST /_ministack/reset
  - list_services                — every emulated service with status badge
  - get_service                  — full info for one service (ops + parity)
  - is_operation_supported       — definitive yes/no for a given (svc, op)
  - search_operations            — substring/verb search across all services
  - list_config_vars             — every env var read by ministack
  - get_config_var               — details on one env var
  - get_endpoint_info            — port, host, auth model

Endpoint URL is configurable via MINISTACK_ENDPOINT_URL
(default http://localhost:4566).
"""

from __future__ import annotations

import json
import os
import re
from typing import Any

import requests
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("MiniStack")

_HERE = os.path.dirname(os.path.abspath(__file__))
_CATALOG_PATH = os.path.join(_HERE, "catalog.json")
_PARITY_PATH = os.path.join(_HERE, "parity.json")
_README_PATH = os.path.join(_HERE, "README.md")


def _endpoint() -> str:
    return os.environ.get("MINISTACK_ENDPOINT_URL", "http://localhost:4566").rstrip("/")


def _load_json(path: str) -> dict:
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


_CATALOG = _load_json(_CATALOG_PATH)
_PARITY = _load_json(_PARITY_PATH)


def _service_record(name: str) -> dict[str, Any] | None:
    svc = _CATALOG.get("services", {}).get(name)
    if not svc:
        return None
    parity = _PARITY.get("services", {}).get(name, {})
    return {
        **svc,
        "status": parity.get("status", "unknown"),
        "real_backend": parity.get("real_backend"),
        "persistence": parity.get("persistence"),
        "multi_tenant": parity.get("multi_tenant"),
        "notes": parity.get("notes"),
        "gotchas": parity.get("gotchas", []),
    }


# ─── MCP Resource: README ────────────────────────────────────────────────────


@mcp.resource("ministack://docs/readme")
def get_readme() -> str:
    if os.path.exists(_README_PATH):
        with open(_README_PATH, "r", encoding="utf-8") as f:
            return f.read()
    return "README.md not found."


# ─── Live probes ─────────────────────────────────────────────────────────────


@mcp.tool()
def ministack_version() -> str:
    """Return the MiniStack version this catalog was built against, plus
    endpoint defaults. Use this first to ground every other answer."""
    info = {
        "ministack_version": _CATALOG.get("ministack_version", "unknown"),
        "catalog_generated_at": _CATALOG.get("generated_at"),
        "endpoint_url": _endpoint(),
        **_CATALOG.get("endpoint", {}),
    }
    return json.dumps(info, indent=2)


@mcp.tool()
def ministack_health() -> str:
    """Probe MINISTACK_ENDPOINT_URL/_ministack/health. Returns live service
    status; if unreachable, the agent should assume MiniStack is not running."""
    try:
        r = requests.get(f"{_endpoint()}/_ministack/health", timeout=2)
        return r.text
    except Exception as e:
        return json.dumps({"error": "unreachable", "endpoint": _endpoint(), "detail": str(e)})


@mcp.tool()
def ministack_reset() -> str:
    """POST MINISTACK_ENDPOINT_URL/_ministack/reset to clear all in-memory
    state. Useful between integration-test scenarios."""
    try:
        requests.post(f"{_endpoint()}/_ministack/reset", timeout=5)
        return json.dumps({"reset": True, "endpoint": _endpoint()})
    except Exception as e:
        return json.dumps({"error": "unreachable", "endpoint": _endpoint(), "detail": str(e)})


@mcp.tool()
def get_endpoint_info() -> str:
    """Return endpoint URL, default port, default account, default region,
    and the auth model (signature is not validated)."""
    info = dict(_CATALOG.get("endpoint", {}))
    info["endpoint_url"] = _endpoint()
    return json.dumps(info, indent=2)


# ─── Catalog reads ───────────────────────────────────────────────────────────


@mcp.tool()
def list_services() -> str:
    """List every emulated service with its status (full, partial, stub,
    paid, unsupported, data-plane) and operation count. Concise overview
    for an agent deciding whether MiniStack covers a given workflow."""
    items = []
    for name in sorted(_CATALOG.get("services", {})):
        rec = _service_record(name) or {}
        items.append({
            "service": name,
            "status": rec.get("status", "unknown"),
            "operation_count": rec.get("operation_count", 0),
            "real_backend": rec.get("real_backend"),
        })
    return json.dumps({"service_count": len(items), "services": items}, indent=2)


@mcp.tool()
def get_service(name: str) -> str:
    """Full info for one service: every supported operation, parity status,
    backend (docker/none), persistence flag, gotchas, and curated notes."""
    rec = _service_record(name)
    if not rec:
        return json.dumps({"error": "service not found", "service": name})
    return json.dumps(rec, indent=2)


@mcp.tool()
def is_operation_supported(service: str, operation: str) -> str:
    """Definitive yes/no for a single (service, operation) pair. Returns
    `supported: true|false` plus the service's status, so the agent can
    distinguish 'not implemented' from 'service is a stub' from 'the verb
    you asked about does not exist on this service in real AWS'."""
    rec = _service_record(service)
    if not rec:
        return json.dumps({
            "service": service,
            "operation": operation,
            "supported": False,
            "reason": "service not emulated by ministack",
        })
    ops = rec.get("operations", [])
    supported = operation in ops
    payload = {
        "service": service,
        "operation": operation,
        "supported": supported,
        "service_status": rec.get("status", "unknown"),
    }
    if not supported:
        payload["reason"] = (
            f"operation not present in catalog for service "
            f"(service has {len(ops)} known operations)"
        )
    return json.dumps(payload, indent=2)


@mcp.tool()
def search_operations(query: str) -> str:
    """Find every operation across every service whose name contains the
    query (case-insensitive). Useful when the agent has a verb in mind
    (e.g. 'PutItem', 'Encrypt') and wants to know which services expose it."""
    q = query.lower()
    if not q:
        return json.dumps({"query": query, "matches": []})
    matches = []
    for svc, data in _CATALOG.get("services", {}).items():
        for op in data.get("operations", []):
            if q in op.lower():
                matches.append({"service": svc, "operation": op})
    return json.dumps({"query": query, "match_count": len(matches), "matches": matches}, indent=2)


@mcp.tool()
def list_config_vars() -> str:
    """List every environment variable that MiniStack reads (MINISTACK_*,
    AWS_*, OPENSEARCH_*, plus a curated extras set). Returns names only —
    use get_config_var(name) for defaults and source files."""
    names = sorted(_CATALOG.get("env_vars", {}).keys())
    return json.dumps({"count": len(names), "env_vars": names}, indent=2)


@mcp.tool()
def get_config_var(name: str) -> str:
    """Details for one env var: default value (if literal), and the
    source files inside ministack/ that read it."""
    var = _CATALOG.get("env_vars", {}).get(name)
    if not var:
        return json.dumps({"error": "env var not found", "name": name})
    return json.dumps(var, indent=2)


def main() -> None:
    mcp.run()


if __name__ == "__main__":
    main()
